-- RBAC: permissions catalog and role/org-member role grants

CREATE TABLE "identity"."permissions" (
    "id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" VARCHAR(80) NOT NULL,
    "resource" VARCHAR(40) NOT NULL,
    "action" VARCHAR(40) NOT NULL,
    "description" VARCHAR(200),

    CONSTRAINT "permissions_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "permissions_code_key" ON "identity"."permissions"("code");

CREATE TABLE "identity"."role_permissions" (
    "role_id" SMALLINT NOT NULL,
    "permission_id" SMALLINT NOT NULL,

    CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("role_id","permission_id")
);

ALTER TABLE "identity"."role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "identity"."roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "identity"."role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "identity"."permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "identity"."org_member_role_permissions" (
    "org_member_role" "customer"."OrgMemberRole" NOT NULL,
    "permission_id" SMALLINT NOT NULL,

    CONSTRAINT "org_member_role_permissions_pkey" PRIMARY KEY ("org_member_role","permission_id")
);

ALTER TABLE "identity"."org_member_role_permissions" ADD CONSTRAINT "org_member_role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "identity"."permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
